dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.view_index, name='index'),

]

greensite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView


urlpatterns = [
    path('', include('showcase.urls')),
    path('products/', include('products.urls')),
    path('ledger/', include('ledger.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    # re_path('djga/', include('google_analytics.urls')),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # import debug_toolbar
    # urlpatterns += [
    #     path('__debug__/', include(debug_toolbar.urls)),
    # ]

ledger/urls.py
from django.urls import path

from . import views

app_name = 'ledger'
urlpatterns = [
    path('', views.view_index, name='index'),

    path('stock/', views.view_stock, name='view_stock'),
    path('funds/', views.view_funds, name='view_funds'),

    path('products/search/', views.product_search, name='products_search'),
    path('counterparties/search/', views.counterparty_search, name='counterparties_search'),

    path('accounts/', views.table_accounts, name='accounts'),
    path('account/add/', views.AccountCreate.as_view(), name='account_add'),
    path('account/<int:pk>/', views.AccountUpdate.as_view(), name='account_edit'),
    path('account/<int:pk>/delete/', views.AccountDelete.as_view(), name='account_delete'),

    path('counterparties/', views.table_counterparties, name='counterparties'),
    path('counterparty/add/', views.CounterpartyCreate.as_view(), name='counterparty_add'),
    path('counterparty/<int:pk>/', views.CounterpartyUpdate.as_view(), name='counterparty_edit'),
    path('counterparty/<int:pk>/delete/', views.CounterpartyDelete.as_view(), name='counterparty_delete'),

    path('customer_orders/', views.table_customer_orders, name='customer_orders'),
    path('customer_order/add/', views.CustomerOrderCreate.as_view(), name='customer_order_add'),
    path('customer_order/<int:pk>/', views.CustomerOrderUpdate.as_view(), name='customer_order_edit'),
    path('customer_order/<int:pk>/delete/', views.CustomerOrderDelete.as_view(), name='customer_order_delete'),
    path('customer_order/<int:pk>/print/', views.CustomerOrderPrint.as_view(), name='customer_order_print'),

    path('customer_order_positions/', views.table_customer_order_positions, name='customer_order_positions'),
    path('customer_order_positions/action', views.CustomerOrderPositionAction.as_view(),
         name='customer_order_position_action'),
    path('customer_order_positions/delete', views.CustomerOrderPositionDelete.as_view(),
         name='customer_order_position_delete'),

    path('customer_order_payments/', views.table_customer_order_payments, name='customer_order_payments'),
    path('customer_order_payments/action', views.CustomerOrderPaymentAction.as_view(),
         name='customer_order_payment_action'),
    path('customer_order_payments/delete', views.CustomerOrderPaymentDelete.as_view(),
         name='customer_order_payment_delete'),
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    # TODO: надо добавить проверку на POST
    path('change_lang/', views.change_lang, name='change_lang'),
    path('', views.list_products, name='list_all'),
    path('<str:blackbox>/edit/', views.edit_product, name='edit_product'),
    path('<str:blackbox>/', views.product_dispatch, name='product'),
]

greensite/views.py
from django.shortcuts import render

# Create your views here.

greensite/templates/greensite/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <title>{{title}} | Greenway</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description"/>
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    {% block extra_css %}
    {% endblock %}
    {%block css%}
    <!-- Toastr Css -->
    <link href="{% static 'libs/toastr/build/toastr.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Bootstrap Css -->
    <link href="{% static 'css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css"/>
    <!-- Icons Css -->
<!--    <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css"/>-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" type="text/css">
    <!-- App Css-->
    <link href="{% static 'css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css"/>
    {%endblock%}

</head>

<body>
<!-- Begin page -->
<div id="layout-wrapper">
    {% block header %}
    {% include 'greensite/header.html' %}
    {% endblock %}
    {% block sidebar %}
    {% include 'greensite/sidebar.html' %}
    {% endblock %}

    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="main-content">

        <div class="page-content">
            <div class="container-fluid">

                <!-- start page title -->
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-flex align-items-center justify-content-between">
                            <h4 class="mb-0">{{title}}</h4>

                            <div class="page-title-right">
                                <ol class="breadcrumb m-0">
                                    <li class="breadcrumb-item"><a href="javascript: void(0);">{{heading}}</a></li>
                                    <li class="breadcrumb-item active">{{title}}</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end page title -->
                {% block content %}
                {% endblock %}
            </div> <!-- container-fluid -->
        </div>
        <!-- End Page-content -->
        {% block footer %}
        {% include 'greensite/footer.html' %}
        {% endblock %}
    </div>
    <!-- end main content-->
</div>
<!-- END layout-wrapper -->

{% block javascript %}
<script src="{% static 'libs/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'libs/metismenu/dist/metisMenu.min.js' %}"></script>
<script src="{% static 'libs/simplebar/dist/simplebar.min.js' %}"></script>
<script src="{% static 'libs/node-waves/dist/waves.min.js' %}"></script>
<script src="{% static 'libs/waypoints/lib/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'libs/jquery.counterup/jquery.counterup.min.js' %}"></script>
<!--TODO: CounterUp should be updated to CounterUp2, waypoints eliminated-->
<script src="{% static 'libs/toastr/build/toastr.min.js' %}"></script>
{% block extra_javascript %}
{% endblock %}

{% if messages %}
<script>
    document.addEventListener("DOMContentLoaded", function(event) {
        toastr.options = { "closeButton": true, "debug": false, "newestOnTop": true,
            "progressBar": false, "positionClass": "toast-top-right", "preventDuplicates": true,
            "onclick": null, "showDuration": "300", "hideDuration": "1000", "timeOut": "5000",
            "extendedTimeOut": "1000", "showEasing": "swing", "hideEasing": "linear",
            "showMethod": "fadeIn", "hideMethod": "fadeOut" };
        {% autoescape off %}
            {% for msg in messages %}
                toastr.{{ msg.level_tag }}("{{ msg }}");
            {% endfor %}
        {% endautoescape %}
    });
</script>
{% endif %}

<script src="{% static 'js/app.js' %}"></script>
{% endblock %}

</body>
</html>

greensite/templates/greensite/footer.html
{% load static %}
{% block footer %}
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                 {% now "Y" %} ©
            </div>
            <div class="col-sm-6">
                <div class="text-sm-end d-none d-sm-block">
                    Crafted with <i class="mdi mdi-heart text-danger"></i> by SantaFox
                </div>
            </div>
        </div>
    </div>
</footer>
{% endblock  %}

greensite/templates/greensite/header.html
{% load static %}
{% block  header %}
<header id="page-topbar">
    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <div class="navbar-brand-box">
                <a href="index.html" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="{% static 'images/logo-sm.png' %}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'images/logo-dark.png' %}" alt="" height="20">
                    </span>
                </a>

                <a href="index.html" class="logo logo-light">
                    <span class="logo-sm">
                        <img src="{% static 'images/logo-sm.png' %}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'images/logo-light.png' %}" alt="" height="20">
                    </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-16 header-item waves-effect vertical-menu-btn">
                <i class="fa fa-fw fa-bars"></i>
            </button>

            <!-- App Search-->
            <form class="app-search d-none d-lg-block">
                <div class="position-relative">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="bi bi-search"></span>
                </div>
            </form>
        </div>

        <div class="d-flex">

            <div class="dropdown d-inline-block d-lg-none ms-2">
                <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-search-dropdown"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="bi bi-search"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0"
                    aria-labelledby="page-header-search-dropdown">

                    <form class="p-3">
                        <div class="m-0">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search ..." aria-label="Recipient's username">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit"><i class="bi bi-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img id="header-lang-img" src="{% static 'images/flags/gb.png' %}" alt="Header Language" height="16">
                </button>
                <div class="dropdown-menu dropdown-menu-end">

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item language" data-lang="en">
                        <img src="{% static 'images/flags/gb.png' %}" alt="user-image" class="me-1" height="12"> <span class="align-middle">English</span>
                    </a>
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item language" data-lang="gr">
                        <img src="{% static 'images/flags/gr.png' %}" alt="user-image" class="me-1" height="12"> <span class="align-middle">Greek</span>
                    </a>
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item language" data-lang="ru">
                        <img src="{% static 'images/flags/ru.png' %}" alt="user-image" class="me-1" height="12"> <span class="align-middle">Russian</span>
                    </a>
                </div>
            </div>

            <div class="dropdown d-none d-lg-inline-block ms-1">
                <button type="button" class="btn header-item noti-icon waves-effect" data-bs-toggle="fullscreen">
                    <i class="bi bi-fullscreen"></i>
                </button>
            </div>

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-notifications-dropdown"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="bi bi-bell"></i>
                    <span class="badge bg-danger rounded-pill">3</span>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0"
                    aria-labelledby="page-header-notifications-dropdown">
                    <div class="p-3">
                        <div class="row align-items-center">
                            <div class="col">
                                <h5 class="m-0 font-size-16"> Notifications </h5>
                            </div>
                            <div class="col-auto">
                                <a href="#!" class="small"> Mark all as read</a>
                            </div>
                        </div>
                    </div>
                    <div data-simplebar style="max-height: 230px;">
                        <a href="" class="text-reset notification-item">
                            <div class="d-flex align-items-start">
                                <div class="flex-shrink-0 me-3">
                                    <div class="avatar-xs">
                                        <span class="avatar-title bg-primary rounded-circle font-size-16">
                                            <i class="uil-shopping-basket"></i>
                                        </span>
                                    </div>
                                </div>
                                <div class="flex-grow-1">
                                    <h6 class="mb-1">Your order is placed</h6>
                                    <div class="font-size-12 text-muted">
                                        <p class="mb-1">If several languages coalesce the grammar</p>
                                        <p class="mb-0"><i class="bi bi-clock"></i> 3 min ago</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                        <a href="" class="text-reset notification-item">
                            <div class="d-flex align-items-start">
                                <div class="flex-shrink-0 me-3">
                                    <img src="{% static 'images/users/avatar-3.jpg' %}" class="rounded-circle avatar-xs" alt="user-pic">
                                </div>
                                <div class="flex-grow-1">
                                    <h6 class="mb-1">James Lemire</h6>
                                    <div class="font-size-12 text-muted">
                                        <p class="mb-1">It will seem like simplified English.</p>
                                        <p class="mb-0"><i class="bi bi-clock"></i> 1 hours ago</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                        <a href="" class="text-reset notification-item">
                            <div class="d-flex align-items-start">
                                <div class="flex-shrink-0 me-3">
                                    <div class="avatar-xs">
                                        <span class="avatar-title bg-success rounded-circle font-size-16">
                                            <i class="uil-truck"></i>
                                        </span>
                                    </div>
                                </div>
                                <div class="flex-grow-1">
                                    <h6 class="mb-1">Your item is shipped</h6>
                                    <div class="font-size-12 text-muted">
                                        <p class="mb-1">If several languages coalesce the grammar</p>
                                        <p class="mb-0"><i class="mdi mdi-clock-outline"></i> 3 min ago</p>
                                    </div>
                                </div>
                            </div>
                        </a>

                        <a href="" class="text-reset notification-item">
                            <div class="d-flex align-items-start">
                                <div class="flex-shrink-0 me-3">
                                    <img src="{% static 'images/users/avatar-4.jpg' %}" class="rounded-circle avatar-xs" alt="user-pic">
                                </div>
                                <div class="flex-grow-1">
                                    <h6 class="mb-1">Salena Layfield</h6>
                                    <div class="font-size-12 text-muted">
                                        <p class="mb-1">As a skeptical Cambridge friend of mine occidental.</p>
                                        <p class="mb-0"><i class="bi bi-clock"></i> 1 hours ago</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="p-2 border-top">
                        <div class="d-grid">
                            <a class="btn btn-sm btn-link font-size-14 text-center" href="javascript:void(0)">
                                <i class="uil-arrow-circle-right me-1"></i> View More..
                            </a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="d-none d-xl-inline-block ms-1 fw-medium font-size-15">{{user.username}}</span>
                    <i class="uil-angle-down d-none d-xl-inline-block font-size-15"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-end">
                    <!-- item-->
                    {% if user.is_authenticated %}
                    <a class="dropdown-item" href="#">
                        <i class="bi bi-person-circle align-middle text-muted me-1"></i>
                        <span class="align-middle">View Profile</span>
                    </a>

                    {% if user.has_usable_password %}
                    <a class="dropdown-item" href="{% url 'password_change' %}">
                        <i class="bi bi-key align-middle text-muted me-1"></i>
                        Change Password
                    </a>
                    {% else %}
                    <a class="dropdown-item" href="{% url 'password_change' %}">
                        <i class="bi bi-key align-middle text-muted me-1"></i>
                        Set Password
                    </a>
                    {% endif %}

                    <a class="dropdown-item d-block" href="#">
                        <i class="bi bi-sliders align-middle me-1 text-muted"></i>
                        <span class="align-middle">Settings</span>
                        <span class="badge bg-soft-success rounded-pill mt-1 ms-2">03</span>
                    </a>

                    {% if user.is_staff %}
                    <a class="dropdown-item" href="{% url 'admin:index' %}">
                        <i class="bi bi-tools align-middle text-muted me-1"></i>
                        Admin Area
                    </a>
                    {% endif %}

                    <a class="dropdown-item text-danger" href="{% url 'logout' %}">
                        <i class="bi bi-door-closed align-middle text-muted me-1"></i>
                        Log Out
                    </a>
                    {% else %}
                    <a class="dropdown-item" href="{% url 'login' %}">
                        <i class="bi bi-door-open font-size-18 align-middle text-muted me-1"></i>
                        Log In
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock  %}

greensite/templates/greensite/sidebar.html
{% load static %}
{% block sidebar %}
<div class="vertical-menu">

    <!-- LOGO -->
    <div class="navbar-brand-box">
        <a href="{% url 'dashboard:index' %}" class="logo logo-dark">
            <span class="logo-sm">
                <img src="{% static 'images/logo-sm.png' %}" alt="" height="22">
            </span>
            <span class="logo-lg">
                <img src="{% static 'images/logo-dark.png' %}" alt="" height="20">
            </span>
        </a>
    </div>

    <button type="button" class="btn btn-sm px-3 font-size-16 header-item waves-effect vertical-menu-btn">
        <i class="fa fa-fw fa-bars"></i>
    </button>

    <div data-simplebar class="sidebar-menu-scroll">

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <li class="menu-title">News</li>

                <li><a href="{% url 'dashboard:index' %}">
                    <i class="bi bi-speedometer2"></i>
                    <span class="badge rounded-pill bg-primary float-end">01</span>
                    <span>Dashboard</span>
                </a></li>

                <li class="menu-title">Catalogue</li>

                <li><a href="{% url 'products:list_all' %}" class=" waves-effect"><i class="uil-cube"></i><span>Products</span></a></li>
                <li><a href="javascript: void(0);" class=" waves-effect"><i class="bi bi-tags"></i><span>Tags</span></a></li>
                <li><a href="javascript: void(0);" class=" waves-effect"><i class="bi bi-percent"></i><span>Current Sales</span></a></li>

                {% if user.is_authenticated %}
                <li class="menu-title">Ledger</li>

                <li><a href="{% url 'ledger:customer_orders' %}" class="waves-effect"><i class="bi bi-bag-check"></i><span>Orders</span></a></li>
                <li><a href="javascript: void(0);" class="waves-effect"><i class="bi bi-truck"></i><span>Supply</span></a></li>
                <li><a href="{% url 'ledger:view_stock' %}" class="waves-effect"><i class="bi bi-boxes"></i><span>Warehouse</span></a></li>
                <li><a href="{% url 'ledger:view_funds' %}" class="waves-effect"><i class="bi bi-piggy-bank"></i><span>Funds</span></a></li>


                <li class="menu-title">Record Book</li>

                <li><a href="{% url 'ledger:accounts' %}" class="waves-effect"><i class="uil-university"></i><span>Accounts</span></a></li>
                <li><a href="{% url 'ledger:counterparties' %}" class="waves-effect"><i class="bi bi-people"></i><span>Counterparties</span></a></li>
                {% endif %}
            </ul>
        </div>
        <!-- Sidebar -->
    </div>
</div>
{% endblock  %}