greensite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView


urlpatterns = [
    path('', include('showcase.urls')),
    path('products/', include('products.urls')),
    path('ledger/', include('ledger.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    # re_path('djga/', include('google_analytics.urls')),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # import debug_toolbar
    # urlpatterns += [
    #     path('__debug__/', include(debug_toolbar.urls)),
    # ]

ledger/urls.py
from django.urls import path

from . import views

app_name = 'ledger'
urlpatterns = [
    path('', views.view_index, name='index'),

    path('stock/', views.view_stock, name='view_stock'),
    path('funds/', views.view_funds, name='view_funds'),

    path('products/search/', views.product_search, name='products_search'),
    path('counterparties/search/', views.counterparty_search, name='counterparties_search'),

    path('accounts/', views.table_accounts, name='accounts'),
    path('account/add/', views.AccountCreate.as_view(), name='account_add'),
    path('account/<int:pk>/', views.AccountUpdate.as_view(), name='account_edit'),
    path('account/<int:pk>/delete/', views.AccountDelete.as_view(), name='account_delete'),

    path('counterparties/', views.table_counterparties, name='counterparties'),
    path('counterparty/add/', views.CounterpartyCreate.as_view(), name='counterparty_add'),
    path('counterparty/<int:pk>/', views.CounterpartyUpdate.as_view(), name='counterparty_edit'),
    path('counterparty/<int:pk>/delete/', views.CounterpartyDelete.as_view(), name='counterparty_delete'),

    path('customer_orders/', views.table_customer_orders, name='customer_orders'),
    path('customer_order/add/', views.CustomerOrderCreate.as_view(), name='customer_order_add'),
    path('customer_order/<int:pk>/', views.CustomerOrderUpdate.as_view(), name='customer_order_edit'),
    path('customer_order/<int:pk>/delete/', views.CustomerOrderDelete.as_view(), name='customer_order_delete'),
    path('customer_order/<int:pk>/print/', views.CustomerOrderPrint.as_view(), name='customer_order_print'),

    path('customer_order_positions/', views.table_customer_order_positions, name='customer_order_positions'),
    path('customer_order_positions/action', views.CustomerOrderPositionAction.as_view(),
         name='customer_order_position_action'),
    path('customer_order_positions/delete', views.CustomerOrderPositionDelete.as_view(),
         name='customer_order_position_delete'),

    path('customer_order_payments/', views.table_customer_order_payments, name='customer_order_payments'),
    path('customer_order_payments/action', views.CustomerOrderPaymentAction.as_view(),
         name='customer_order_payment_action'),
    path('customer_order_payments/delete', views.CustomerOrderPaymentDelete.as_view(),
         name='customer_order_payment_delete'),
]

ledger/views.py
from datetime import datetime, date
from itertools import groupby
from operator import itemgetter

from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import OuterRef, Sum, Subquery, Value, Func, F, DecimalField, Case, When, Q, FilteredRelation
from django.db.models.functions import Coalesce, Cast
from django.http import JsonResponse, Http404, HttpResponseBadRequest
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from django_tables2 import RequestConfig
from crispy_forms.utils import render_crispy_form

from greensite.decorators import prepare_languages
from products.models import Product

from .models import Account, Counterparty, Operation, CustomerOrder, CustomerOrderPosition, SupplierOrderPosition, \
    ItemSetBreakdownPosition, Payment, Transfer, DEBIT, CREDIT
from .tables import InStockTable, FundsTable, AccountsTable, CounterpartyTable, CustomerOrdersTable, \
    CustomerOrderPositionsTable, CustomerOrderPaymentsTable
from .forms import AccountForm, CounterpartyForm, CustomerOrderForm, CustomerOrderPositionForm, CustomerOrderPaymentForm
from .filters import CustomerOrderFilter
from .classes import CrudActionView, CrudDeleteView


@login_required
@prepare_languages
def view_index(request):
    return TemplateResponse(request, 'ledger/index.html')


@login_required
@prepare_languages
def view_stock(request):
    date_report = datetime.strptime(request.GET.get("reportDate", date.today().strftime("%Y-%m-%d")), "%Y-%m-%d").date()

    dict_customer_orders = {pos.get('Product__SKU'): pos for pos in CustomerOrderPosition.objects \
        .values('Product__SKU') \
        .annotate(
            delivered=Sum(Case(
                When(Q(Operation__customerorder__DetailedDelivery=True) &
                     Q(DateDelivered__lte=date_report),
                     Operation__DateOperation__lte=date_report,
                     then=F('Quantity')),
                When(Q(Operation__customerorder__DetailedDelivery=False) &
                     Q(Operation__customerorder__DateDelivered__lte=date_report),
                     Operation__DateOperation__lte=date_report,
                     then=F('Quantity')),
                default=0)),
            not_delivered=Sum(Case(
                When(Q(Operation__customerorder__DetailedDelivery=True) &
                     (Q(DateDelivered__isnull=True) | Q(DateDelivered__gt=date_report)),
                     Operation__DateOperation__lte=date_report,
                     then=F('Quantity')),
                When(Q(Operation__customerorder__DetailedDelivery=False) &
                     (Q(Operation__customerorder__DateDelivered__isnull=True) |
                      Q(Operation__customerorder__DateDelivered__gt=date_report)),
                     Operation__DateOperation__lte=date_report,
                     then=F('Quantity')),
                default=0)),
            not_delivered_4=Sum(Case(
                When(Q(Operation__customerorder__DetailedDelivery=True) &
                     (Q(DateDelivered__isnull=True) | Q(DateDelivered__gt=date_report)),
                     Operation__DateOperation__lte=date_report,
                     Status=4,
                     then=F('Quantity')),
                When(Q(Operation__customerorder__DetailedDelivery=False) &
                     (Q(Operation__customerorder__DateDelivered__isnull=True) |
                      Q(Operation__customerorder__DateDelivered__gt=date_report)),
                     Operation__DateOperation__lte=date_report,
                     Status=4,
                     then=F('Quantity')),
                default=0)),
        ).order_by('Product__SKU')}

    dict_supplier_orders = {pos.get('Product__SKU'): pos for pos in SupplierOrderPosition.objects \
        .values('Product__SKU') \
        .annotate(
            delivered=Sum(Case(
                When(Q(Operation__supplierorder__DateDelivered__lte=date_report),
                     Operation__DateOperation__lte=date_report,
                     then=F('Quantity')),
                default=0)),
            not_delivered=Sum(Case(
                When(Q(Operation__supplierorder__DateDelivered__isnull=True) |
                     Q(Operation__supplierorder__DateDelivered__gt=date_report),
                     Operation__DateOperation__lte=date_report,
                     then=F('Quantity')),
                default=0)),
        ).order_by('Product__SKU')}

    dict_breakdowns = {pos.get('Product__SKU'): pos for pos in ItemSetBreakdownPosition.objects \
        .values('Product__SKU') \
        .annotate(
            received=Sum(Case(
                When(TransactionType=CREDIT, Operation__DateOperation__lte=date_report, then=F('Quantity')),
                default=0)),
            removed=Sum(Case(
                When(TransactionType=DEBIT, Operation__DateOperation__lte=date_report, then=F('Quantity')),
                default=0)),
        ).order_by('Product__SKU')}

    query_products = Product.objects \
        .annotate(pi=FilteredRelation('productinfo', condition=Q(productinfo__Language=request.language_instance))) \
        .values('SKU', 'Category__Name', 'pi__Name').order_by('Category__Name', 'SKU') \

    list_total_stock = []
    for p in query_products:
        list_total_stock.append(
            dict(
                product_SKU=p['SKU'],
                product_name=p['pi__Name'],
                product_category=p['Category__Name'],
                cust_delivered=dict_customer_orders.get(p['SKU'], {}).get('delivered') or 0,
                cust_not_delivered=dict_customer_orders.get(p['SKU'], {}).get('not_delivered') or 0,
                cust_not_delivered_4=dict_customer_orders.get(p['SKU'], {}).get('not_delivered_4') or 0,
                supp_delivered=dict_supplier_orders.get(p['SKU'], {}).get('delivered') or 0,
                supp_not_delivered=dict_supplier_orders.get(p['SKU'], {}).get('not_delivered') or 0,
                break_received=dict_breakdowns.get(p['SKU'], {}).get('received') or 0,
                break_removed=dict_breakdowns.get(p['SKU'], {}).get('removed') or 0,
            )
        )
    # Remove rows for products that were never processed
    list_in_stock = [i for i in list_total_stock if
                     i['cust_delivered'] != 0 or i['cust_not_delivered'] != 0 or
                     i['supp_delivered'] != 0 or i['supp_not_delivered'] != 0 or
                     i['break_received'] != 0 or i['break_removed'] != 0]

    # Prepare sum values and filter positions not in stock if requested
    for p in list_in_stock:
        p["in_stock"] = p["supp_delivered"] - p["cust_delivered"] + p['break_received'] - p['break_removed']
    if request.GET.get("collapse", "false") == "true":
        list_in_stock = [i for i in list_in_stock
                         if (i["in_stock"] != 0) | (i["supp_not_delivered"] != 0) | (i["cust_not_delivered"] != 0)]

    table = InStockTable(list_in_stock)

    RequestConfig(request, paginate=False).configure(table)

    return TemplateResponse(request, 'ledger/table_stocks.html', {
        'table': table,
        'reportDate': date_report,
    })


@login_required
@prepare_languages
def view_funds(request):
    date_start = datetime.strptime(request.GET.get("startDate", '2022-01-01'), "%Y-%m-%d").date()
    date_end = datetime.strptime(request.GET.get("endDate", '2022-12-31'), "%Y-%m-%d").date()

    qry_payments = Payment.objects \
        .values(account=F('Account__Name'), currency=F('Currency__Code')) \
        .annotate(
            initial=Sum(Case(
                When(Q(DateOperation__lt=date_start),
                     TransactionType=DEBIT,
                     then=F('Amount') * -1),
                When(Q(DateOperation__lt=date_start),
                     TransactionType=CREDIT,
                     then=F('Amount') * 1),
                output_field=DecimalField(),
                default=0)),
            debited=Sum(Case(
                When(Q(DateOperation__gte=date_start) & Q(DateOperation__lte=date_end),
                     TransactionType=DEBIT,
                     then=F('Amount')),
                output_field=DecimalField(),
                default=0)),
            credited=Sum(Case(
                When(Q(DateOperation__gte=date_start) & Q(DateOperation__lte=date_end),
                     TransactionType=CREDIT,
                     then=F('Amount')),
                output_field=DecimalField(),
                default=0)),
        )

    qry_transfers_debits = Transfer.objects \
        .values(account=F('DebitAccount__Name'), currency=F('DebitCurrency__Code')) \
        .annotate(
            initial=Sum(Case(
                When(Q(DateOperation__lt=date_start),
                     then=F('DebitAmount') * -1),
                output_field=DecimalField(),
                default=0)),
            debited=Sum(Case(
                When(Q(DateOperation__gte=date_start) & Q(DateOperation__lte=date_end),
                     then=F('DebitAmount')),
                output_field=DecimalField(),
                default=0)),
            credited=Value(0),
        ).exclude(DebitAccount__isnull=True)

    qry_transfers_credits = Transfer.objects \
        .values(account=F('CreditAccount__Name'), currency=F('CreditCurrency__Code')) \
        .annotate(
            initial=Sum(Case(
                When(Q(DateOperation__lt=date_start),
                     then=F('CreditAmount')),
                output_field=DecimalField(),
                default=0)),
            debited=Value(0),
            credited=Sum(Case(
                When(Q(DateOperation__gte=date_start) & Q(DateOperation__lte=date_end),
                     then=F('CreditAmount')),
                output_field=DecimalField(),
                default=0)),
        ).exclude(CreditAccount__isnull=True)

ledger/views/accounts.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.template.response import TemplateResponse
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from greensite.decorators import prepare_languages

from ledger.models import Account
from ledger.forms import AccountForm


@login_required
@permission_required('ledger.view_account', raise_exception=True)
@prepare_languages
def table_accounts(request):
    qst = Account.objects.filter(User=request.user)

    return TemplateResponse(request, 'ledger/ecommerce-accounts.html', {
        'title': 'Accounts',
        'heading': 'Ledger',
        'table': qst,
    })


class AccountCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Account
    form_class = AccountForm
    success_message = "Account %(Name)s successfully created"
    success_url = reverse_lazy('ledger:accounts')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add Account'
        context['heading'] = 'Ledger'
        return context

    # def get_initial(self):
    #     initial = super().get_initial()
    #     initial = initial.copy()
    #     initial['User_id'] = self.request.user.pk
    #     return initial

    def form_valid(self, form):
        form.instance.User = self.request.user
        return super().form_valid(form)


class AccountUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Account
    form_class = AccountForm
    success_message = "Account %(Name)s successfully updated"
    success_url = reverse_lazy('ledger:accounts')

    def form_valid(self, form):
        if not form.has_changed():
            form.add_error(None, 'Form data was not changed')
            return super().form_invalid(form)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edit Account'
        context['heading'] = 'Ledger'
        return context


class AccountDelete(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = Account
    success_message = "Account successfully deleted"
    success_url = reverse_lazy('ledger:accounts')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Delete Account'
        context['heading'] = 'Ledger'

        object_instance = self.get_object()
        related = object_instance.is_deletable()
        if related:
            related_dict = {
                str(rel.model._meta.verbose_name_plural): list(i.__str__() for i in rel.all()) for rel in related
            }
            context['related'] = related_dict

        return context

ledger/templates/ledger/account_form.html
{% extends 'greensite/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Textual inputs</h4>
                <p class="card-title-desc">Here are examples of <code>.form-control</code> applied to each
                    textual HTML5 <code>&lt;input&gt;</code> <code>type</code>.</p>
                <form method="post">{% csrf_token %}
                    {% crispy form %}
                    <div class="row mb-4">
                        <div class="col ms-auto">
                            <div class="d-flex flex-reverse flex-wrap gap-2">
                                <button type="submit" class="btn btn-success w-lg waves-effect waves-light me-1">
                                    Save
                                </button>
                                <a role="button" class="btn btn-info w-lg waves-effect" href="{% url 'ledger:accounts' %}">
                                    Cancel
                                </a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ledger/templates/ledger/counterparty_confirm_delete.html
{% extends 'greensite/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row" xmlns="http://www.w3.org/1999/html">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <h4 class="card-title">Object deletion</h4>
                <p class="card-title-desc">Deletion of any object is possible only in case if there is no related objects.</p>

                <form method="post">{% csrf_token %}
                    {% if related %}
                    <p class="text-danger">Object deletion is impossible, the following related objects are found:</p>
                    <ul>
                        {% for rel_class, rel_list in related.items %}
                        <li>{{ rel_class }}</li>
                            <ul>
                                {% for rel_obj in rel_list %}
                                <li>{{ rel_obj }}</li>
                                {% endfor %}
                            </ul>
                        {% endfor %}
                    </ul>
                    <div class="row mb-4">
                        <div class="col ms-auto">
                            <div class="d-flex flex-reverse flex-wrap gap-2">
                                <a role="button" class="btn btn-info w-lg waves-effect" href="{% url 'ledger:counterparties' %}">
                                    OK
                                </a>
                            </div>
                        </div>
                    </div>
                    {% else %}
                    <p>There is no related objects, you can proceed with the deletion.</p>
                    <div class="row mb-4">
                        <div class="col ms-auto">
                            <div class="d-flex flex-reverse flex-wrap gap-2">
                                <button type="submit" class="btn btn-danger waves-effect waves-light me-1">
                                    Confirm Delete
                                </button>
                                <a role="button" class="btn btn-info w-lg waves-effect" href="{% url 'ledger:counterparties' %}">
                                    Cancel
                                </a>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </form>
            </div>
        </div>  <!-- end card -->
    </div>   <!-- end column -->
</div>
{% endblock %}

{% block extra_javascript %}
<!-- init js -->
<script src="{% static 'js/pages/ecommerce-add-product.init.js' %}"></script>
{% endblock  %}

ledger/templates/ledger/ecommerce-accounts.html
{% extends 'greensite/base.html' %}
{% load static %}

{% block extra_css %}
<link href="{% static 'libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css"/>
{% endblock  %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div>
            <a role="button" href="{% url 'ledger:account_add' %}" class="btn btn-success waves-effect waves-light mb-3">
                <i class="mdi mdi-plus me-1"></i> Add Account
            </a>
        </div>

        <div class="table-responsive mb-4">
            <table class="table table-centered datatable dt-responsive nowrap table-card-list"
                   style="border-collapse: collapse; border-spacing: 0 12px; width: 100%;">
                <thead>
                <tr class="bg-transparent">
                    <th>Name</th>
                    <th style="width: 120px;">Action</th>
                </tr>
                </thead>
                <tbody>
                {% for customer in table %}
                <tr>
                    <td>{{ customer.Name }}</td>
                    <td>
                        <a href="{% url 'ledger:account_edit' customer.pk %}" class="px-3 text-primary">
                            <i class="bi bi-pencil-square font-size-18"></i>
                        </a>
                        <a href="{% url 'ledger:account_delete' customer.pk %}" class="px-3 text-danger">
                            <i class="bi bi-trash font-size-18"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_javascript %}
<script src="{% static 'libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

<!-- init js -->
<script src="{% static 'ledger/accounts.init.js' %}"></script>
{% endblock  %}

ledger/templates/ledger/ecommerce-customers.html
{% extends 'greensite/base.html' %}
{% load static %}

{% block extra_css %}
<link href="{% static 'libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css"/>
{% endblock  %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div>
            <div class="float-end">
                <form class="d-inline-flex mb-3">
                    <label class="form-check-label my-2 me-2" for="order-selectinput">Show&nbsp;Counterparties</label>
                    <select class="form-select" id="order-selectinput">
                        <option select value="0">All</option>
                        <option value="1">Only Customers</option>
                        <option value="2">Only Suppliers</option>
                    </select>
                </form>
            </div>
            <a role="button" href="{% url 'ledger:counterparty_add' %}" class="btn btn-success waves-effect waves-light mb-3">
                <i class="mdi mdi-plus me-1"></i> Add Customer
            </a>
        </div>

        <div class="table-responsive mb-4">
            <table class="table table-centered datatable dt-responsive nowrap table-card-list"
                   style="border-collapse: collapse; border-spacing: 0 12px; width: 100%;">
                <thead>
                <tr class="bg-transparent">
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>City</th>
                    <th>Memo</th>
                    <th>Is Customer</th>
                    <th>Is Supplier</th>
                    <th>Role</th>
                    <th style="width: 120px;">Action</th>
                </tr>
                </thead>
                <tbody>
                {% for customer in table %}
                <tr>
                    <td>{{ customer.Name }}</td>
                    <td>{{ customer.Phone }}</td>
                    <td>{{ customer.Email }}</td>
                    <td>{{ customer.City }}</td>
                    <td>{{ customer.Memo|truncatechars:40 }}</td>
                    <td>{{ customer.IsCustomer }}</td>
                    <td>{{ customer.IsSupplier }}</td>
                    <td>
                        {% if customer.IsCustomer %}
                        <div class="badge rounded-pill bg-soft-success font-size-12">Customer</div>
                        {% endif %} {% if customer.IsSupplier %}
                        <div class="badge rounded-pill bg-soft-primary font-size-12">Supplier</div>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'ledger:counterparty_edit' customer.pk %}" class="px-3 text-primary">
                            <i class="bi bi-pencil-square font-size-18"></i>
                        </a>
                        <a href="{% url 'ledger:counterparty_delete' customer.pk %}" class="px-3 text-danger">
                            <i class="bi bi-trash font-size-18"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_javascript %}
<script src="{% static 'libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

<!-- init js -->
<script src="{% static 'ledger/counterparties.init.js' %}"></script>
{% endblock  %}

ledger/templates/ledger/ecommerce-orders.html
{% extends 'greensite/base.html' %}
{% load static %}

{% block extra_css %}
<link href="{% static 'libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css"/>
{% endblock  %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div>
            <div class="float-end">
                <form class="d-inline-flex mb-3">
                    <label class="form-check-label my-2 me-2" for="order-selectinput">Orders</label>
                    <select class="form-select" id="order-selectinput">
                        <option value="0">All</option>
                        <option selected value="1">Active</option>
                        <option value="2">(Pending)</option>
                        <option value="3">Not delivered</option>
                        <option value="4">Not paid</option>
                        <option value="5">Completed</option>
                    </select>
                </form>
            </div>
            <a role="button" href="{% url 'ledger:customer_order_add' %}"
               class="btn btn-success waves-effect waves-light mb-3">
                <i class="mdi mdi-plus me-1"></i> Add New Order
            </a>
        </div>

        <div class="table-responsive mb-4">
            <table class="table table-centered datatable dt-responsive nowrap table-card-list"
                   style="border-collapse: collapse; border-spacing: 0 12px; width: 100%;">
                <thead>
                <tr class="bg-transparent">
                    <th>Date</th>
                    <th>Customer</th>
                    <th>Amount</th>
                    <th>Paid Amount</th>
                    <th>Currency</th>
                    <th>Payment</th>
                    <th>Delivery</th>
                    <th>Comment</th>
                    <th style="width: 120px;">Action</th>
                </tr>
                </thead>
                <tbody>
                {% for order in orders %}
                <tr>
                    <td data-sort="{{ order.DateOperation|date:'U' }}">
                        {{ order.DateOperation|date:'d.m.y' }}
                    </td>
                    <td>{{ order.Customer.Name }}</td>
                    <td>{{ order.get_order_amount|floatformat:2 }}</td>
                    <td>{{ order.get_paid_amount|floatformat:2 }}</td>
                    <td>{{ order.Currency.Code }}</td>
                    {% if order.get_order_amount == 0 %}
                    <td><div class="badge bg-soft-info font-size-12">Empty Order</div></td>
                    {% elif order.get_paid_amount == 0 %}
                    <td><div class="badge bg-soft-danger font-size-12">Not Paid</div></td>
                    {% elif order.get_paid_amount == order.get_order_amount %}
                    <td><div class="badge bg-soft-success font-size-12">Paid</div></td>
                    {% elif order.get_paid_amount < order.get_order_amount %}
                    <td><div class="badge bg-soft-warning font-size-12">Partially Paid</div></td>
                    {% elif order.get_paid_amount > order.get_order_amount %}
                    <td><div class="badge bg-soft-warning font-size-12">Overpaid</div></td>
                    {% endif %}
                    <td>{{ order.DateDelivered|date:'d.m.y' }}</td>
                    <td>{{ order.Memo|truncatechars:30 }}</td>
                    <td>
                        <a href="{% url 'ledger:customer_order_print' order.pk %}" class="px-2 text-dark">
                            <i class="bi bi-printer font-size-18"></i>
                        </a>
                        <a href="{% url 'ledger:customer_order_edit' order.pk %}" class="px-2 text-primary">
                            <i class="bi bi-pencil-square font-size-18"></i>
                        </a>
                        <a href="{% url 'ledger:customer_order_delete' order.pk %}" class="px-2 text-danger">
                            <i class="bi bi-trash font-size-18"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_javascript %}
<script src="{% static 'libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

<!-- init js -->
<script src="{% static 'ledger/orders.init.js' %}"></script>
{% endblock  %}

ledger/templates/ledger/index.html
{% extends "greensite/base.html" %}

{% block title %}GreenWay Cyprus{% endblock %}

{% block content %}
<p>Ledger</p>
{% endblock %}